package: hyphenator
version: '2.0.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/hyphenator

page:
    title: 'translate:title'
    perm: hyphenator[]
    pjax: true
    icon: rex-icon fa-file-text-o
    subpages:
        demo: { title: 'translate:demo', perm: hyphenator[] }
        config: { title: 'translate:config', perm: hyphenator[config] }

requires:
    redaxo: '>=5.19.0'
    php: '>=8.4'
