package: hyphenator
version: '1.1.5'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/hyphenator

page:
    title: 'translate:title'
    perm: hyphenator[]
    pjax: true
    icon: rex-icon fa-file-text-o
    subpages:
        config: { title: 'translate:config', perm: hyphenator[config] }